name: measure_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.5.0"

dependencies:
  dchs_motion_sensors:
  video_player:
  fl_chart:
  http:
  web_socket_channel:
  flutter_udid:
  auto_size_text:
  flutter:
    sdk: flutter
  async: ^2.11.0
  characters: ^1.3.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  string_scanner: ^1.2.0
  camera: ^0.11.0+2
  # sensors_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  fake_async: ^1.3.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  lints: ^5.0.0
  matcher: ^0.12.16+1
  stack_trace: ^1.11.0
  test_api: ^0.7.2
  vm_service: ^14.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Black.otf
        - asset: fonts/NotoSansJP-Bold.otf
        - asset: fonts/NotoSansJP-Light.otf
        - asset: fonts/NotoSansJP-Medium.otf
        - asset: fonts/NotoSansJP-Regular.otf
        - asset: fonts/NotoSansJP-Thin.otf
